# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo Document' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo Document
  
  pod 'brscan-sdk-documento-ios' , '4.1.1-dynamic-nobitcode'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|

      config.build_settings['ENABLE_BITCODE'] = 'YES'
    end
  end
end

